<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFrameworks>NET5;NET6;NET8;NET9;NET10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>1.0.0</Version>
    <Authors>LHZ</Authors>
    <Description>A lightweight ASP.NET Core middleware wrapper for the LHZ.WebSocket library, enabling WebSocket upgrade handling and client tracking in ASP.NET Core applications.</Description>
    <PackageIcon>logo.png</PackageIcon>
    <RepositoryType>Git</RepositoryType>
    <RepositoryUrl>https://github.com/lhzcm/LHZ.WebSocket.AspNetCore</RepositoryUrl>
    <PackageReleaseNotes>1.0.0：Initial release</PackageReleaseNotes>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/lhzcm/LHZ.WebSocket.AspNetCore</PackageProjectUrl>
    <PackageTags>websocket,aspnetcore</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LHZ.WebSocket" Version="1.0.2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.zh-CN.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="logo.png">
      <Pack>True</Pack>
      <PackagePath />
    </None>
  </ItemGroup>
</Project>